dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

dotenv: .env
networks:
  default: ganache-local-1
  rinkeby:
    eth_usd_price_feed: "0x3D2659882a70421498E8953A662dDdd95591Be77"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local-1:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
